// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Needly.Infrastructure;

#nullable disable

namespace Needly.Infrastructure.Migrations
{
    [DbContext(typeof(NeedlyDbContext))]
    [Migration("20260903035521_InitialSqlServer")]
    partial class InitialSqlServer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Needly.Domain.ActionDisposition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFyi")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit");

                    b.Property<Guid>("NeedlyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("SnoozedUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("NeedlyUserId", "ActionId")
                        .IsUnique();

                    b.HasIndex("NeedlyUserId", "IsArchived", "IsMuted", "SnoozedUntil", "IsPinned");

                    b.ToTable("ActionDispositions", (string)null);
                });

            modelBuilder.Entity("Needly.Domain.ActionEventReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DetectorKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EventId", "DetectorKey")
                        .IsUnique();

                    b.ToTable("ActionEventReceipts", (string)null);
                });

            modelBuilder.Entity("Needly.Domain.ActionLifecycleUndo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AppliedState")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("NeedlyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("PreviousSnoozedUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PreviousState")
                        .HasColumnType("int");

                    b.Property<Guid?>("SuppressionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("SuppressionId");

                    b.HasIndex("NeedlyUserId", "CreatedAt");

                    b.ToTable("ActionLifecycleUndos", (string)null);
                });

            modelBuilder.Entity("Needly.Domain.ActionSuppression", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssigneeType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("NeedlyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SubjectNumber")
                        .HasColumnType("int");

                    b.Property<int>("SubjectType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("InstallationId", "RepositoryId", "SubjectType", "SubjectNumber", "AssigneeType", "AssigneeId", "IsActive");

                    b.HasIndex("NeedlyUserId", "InstallationId", "RepositoryId", "SubjectType", "SubjectNumber", "AssigneeType", "AssigneeId")
                        .IsUnique()
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("ActionSuppressions", (string)null);
                });

            modelBuilder.Entity("Needly.Domain.AutomationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Effect")
                        .HasColumnType("int");

                    b.Property<string>("FilterJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("NeedlyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<TimeSpan?>("SnoozeDuration")
                        .HasColumnType("time");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("NeedlyUserId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("NeedlyUserId", "SortOrder");

                    b.ToTable("AutomationRules", (string)null);
                });

            modelBuilder.Entity("Needly.Domain.GitHubUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("GitHubUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("GitHubUserId")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("GitHubUsers", (string)null);
                });

            modelBuilder.Entity("Needly.Domain.Installation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("GitHubAccountId")
                        .HasColumnType("bigint");

                    b.Property<long>("GitHubInstallationId")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("GitHubInstallationId")
                        .IsUnique();

                    b.ToTable("Installations", (string)null);
                });

            modelBuilder.Entity("Needly.Domain.InstallationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("GitHubUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("GitHubUserId", "IsActive");

                    b.HasIndex("InstallationId", "GitHubUserId")
                        .IsUnique();

                    b.ToTable("InstallationMembers", (string)null);
                });

            modelBuilder.Entity("Needly.Domain.NeedlyAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssigneeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AssigneeType")
                        .HasColumnType("int");

                    b.Property<string>("AuthorLogin")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Context")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("HasBotInvolvement")
                        .HasColumnType("bit");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAtRisk")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RiskReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("SnoozedUntil")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("SubjectNumber")
                        .HasColumnType("int");

                    b.Property<int>("SubjectType")
                        .HasColumnType("int");

                    b.Property<string>("SubjectUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("WaitingSince")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasFilter("[State] IN (0, 1)");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("State", "IsAtRisk", "LastActivityAt");

                    b.HasIndex("InstallationId", "AssigneeType", "AssigneeId", "State", "UpdatedAt");

                    b.HasIndex("Type", "RepositoryId", "SubjectType", "SubjectNumber", "AssigneeType", "AssigneeId")
                        .IsUnique()
                        .HasFilter("[State] IN (0, 1)");

                    b.ToTable("Actions", (string)null);
                });

            modelBuilder.Entity("Needly.Domain.NeedlyUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<Guid>("GitHubUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("OnboardingCompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GitHubUserId")
                        .IsUnique();

                    b.ToTable("NeedlyUsers", (string)null);
                });

            modelBuilder.Entity("Needly.Domain.RawEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventAction")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<long>("GitHubInstallationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("GitHubRepositoryId")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("InstallationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId")
                        .IsUnique();

                    b.HasIndex("InstallationId");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.HasIndex("GitHubInstallationId", "GitHubRepositoryId", "ReceivedAt");

                    b.ToTable("RawEvents", (string)null);
                });

            modelBuilder.Entity("Needly.Domain.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("GitHubRepositoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("HistoricalBootstrapCompletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("HistoricalBootstrapStartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId", "GitHubRepositoryId")
                        .IsUnique();

                    b.HasIndex("Owner", "Name")
                        .IsUnique();

                    b.ToTable("Repositories", (string)null);
                });

            modelBuilder.Entity("Needly.Domain.RuleExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ActionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Effect")
                        .HasColumnType("int");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(140)
                        .HasColumnType("nvarchar(140)");

                    b.Property<Guid>("NeedlyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RuleOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActionId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("NeedlyUserId", "ExecutedAt");

                    b.ToTable("RuleExecutions", (string)null);
                });

            modelBuilder.Entity("Needly.Domain.SavedView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FilterJson")
                        .IsRequired()
                        .HasMaxLength(16000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("NeedlyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("NeedlyUserId", "NormalizedName")
                        .IsUnique();

                    b.HasIndex("NeedlyUserId", "SortOrder");

                    b.ToTable("SavedViews", (string)null);
                });

            modelBuilder.Entity("Needly.Domain.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("GitHubTeamId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("InstallationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("InstallationId", "GitHubTeamId")
                        .IsUnique();

                    b.HasIndex("InstallationId", "Slug")
                        .IsUnique();

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("Needly.Domain.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("GitHubUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("GitHubUserId", "IsActive");

                    b.HasIndex("TeamId", "GitHubUserId")
                        .IsUnique();

                    b.ToTable("TeamMembers", (string)null);
                });

            modelBuilder.Entity("Needly.Domain.UserInstallation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("GitHubInstallationId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("NeedlyUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NeedlyUserId", "GitHubInstallationId")
                        .IsUnique();

                    b.ToTable("UserInstallations", (string)null);
                });

            modelBuilder.Entity("Needly.Infrastructure.GitHub.GitHubCheckFailureStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CheckKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HeadSha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsFailing")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PullRequestNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "PullRequestNumber", "HeadSha", "CheckKey")
                        .IsUnique();

                    b.ToTable("GitHubCheckFailureStates", (string)null);
                });

            modelBuilder.Entity("Needly.Infrastructure.GitHub.GitHubPullRequestStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ApprovalCount")
                        .HasColumnType("int");

                    b.Property<long>("AuthorGitHubUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("AuthorLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CheckState")
                        .HasColumnType("int");

                    b.Property<bool?>("HasChangesRequested")
                        .HasColumnType("bit");

                    b.Property<bool?>("HasConflicts")
                        .HasColumnType("bit");

                    b.Property<string>("HeadSha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsMergeable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("bit");

                    b.Property<int>("PullRequestNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ReadinessCheckedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "PullRequestNumber")
                        .IsUnique();

                    b.ToTable("GitHubPullRequestStates", (string)null);
                });

            modelBuilder.Entity("Needly.Infrastructure.GitHub.GitHubResponseStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("GitHubAssigneeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPending")
                        .HasColumnType("bit");

                    b.Property<long>("LastTriggerCommentId")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("LastTriggeredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SubjectNumber")
                        .HasColumnType("int");

                    b.Property<int>("SubjectType")
                        .HasColumnType("int");

                    b.Property<int>("TriggerCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "SubjectType", "SubjectNumber", "GitHubAssigneeId")
                        .IsUnique();

                    b.ToTable("GitHubResponseStates", (string)null);
                });

            modelBuilder.Entity("Needly.Infrastructure.GitHub.GitHubReviewRequestStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssigneeLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AssigneeType")
                        .HasColumnType("int");

                    b.Property<long>("GitHubAssigneeId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsRequested")
                        .HasColumnType("bit");

                    b.Property<int>("PullRequestNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "PullRequestNumber", "AssigneeType", "GitHubAssigneeId")
                        .IsUnique();

                    b.ToTable("GitHubReviewRequestStates", (string)null);
                });

            modelBuilder.Entity("Needly.Infrastructure.GitHub.GitHubReviewerFeedbackStateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApproximateUnresolvedCommentCount")
                        .HasColumnType("int");

                    b.Property<bool>("HasOutstandingChanges")
                        .HasColumnType("bit");

                    b.Property<int>("PullRequestNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ReviewId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReviewerGitHubUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReviewerLogin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "PullRequestNumber", "ReviewerGitHubUserId")
                        .IsUnique();

                    b.ToTable("GitHubReviewerFeedbackStates", (string)null);
                });

            modelBuilder.Entity("Needly.Domain.ActionDisposition", b =>
                {
                    b.HasOne("Needly.Domain.NeedlyAction", null)
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Needly.Domain.NeedlyUser", null)
                        .WithMany()
                        .HasForeignKey("NeedlyUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Needly.Domain.ActionEventReceipt", b =>
                {
                    b.HasOne("Needly.Domain.RawEvent", null)
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Needly.Domain.ActionLifecycleUndo", b =>
                {
                    b.HasOne("Needly.Domain.NeedlyAction", null)
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Needly.Domain.NeedlyUser", null)
                        .WithMany()
                        .HasForeignKey("NeedlyUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Needly.Domain.ActionSuppression", null)
                        .WithMany()
                        .HasForeignKey("SuppressionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Needly.Domain.ActionSuppression", b =>
                {
                    b.HasOne("Needly.Domain.Installation", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Needly.Domain.NeedlyUser", null)
                        .WithMany()
                        .HasForeignKey("NeedlyUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Needly.Domain.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Needly.Domain.AutomationRule", b =>
                {
                    b.HasOne("Needly.Domain.NeedlyUser", null)
                        .WithMany()
                        .HasForeignKey("NeedlyUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Needly.Domain.InstallationMember", b =>
                {
                    b.HasOne("Needly.Domain.GitHubUser", null)
                        .WithMany()
                        .HasForeignKey("GitHubUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Needly.Domain.Installation", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Needly.Domain.NeedlyAction", b =>
                {
                    b.HasOne("Needly.Domain.Installation", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Needly.Domain.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Needly.Domain.NeedlyUser", b =>
                {
                    b.HasOne("Needly.Domain.GitHubUser", null)
                        .WithOne()
                        .HasForeignKey("Needly.Domain.NeedlyUser", "GitHubUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Needly.Domain.RawEvent", b =>
                {
                    b.HasOne("Needly.Domain.Installation", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Needly.Domain.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Needly.Domain.Repository", b =>
                {
                    b.HasOne("Needly.Domain.Installation", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Needly.Domain.RuleExecution", b =>
                {
                    b.HasOne("Needly.Domain.NeedlyAction", null)
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Needly.Domain.NeedlyUser", null)
                        .WithMany()
                        .HasForeignKey("NeedlyUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Needly.Domain.SavedView", b =>
                {
                    b.HasOne("Needly.Domain.NeedlyUser", null)
                        .WithMany()
                        .HasForeignKey("NeedlyUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Needly.Domain.Team", b =>
                {
                    b.HasOne("Needly.Domain.Installation", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Needly.Domain.TeamMember", b =>
                {
                    b.HasOne("Needly.Domain.GitHubUser", null)
                        .WithMany()
                        .HasForeignKey("GitHubUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Needly.Domain.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Needly.Domain.UserInstallation", b =>
                {
                    b.HasOne("Needly.Domain.NeedlyUser", null)
                        .WithMany()
                        .HasForeignKey("NeedlyUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Needly.Infrastructure.GitHub.GitHubCheckFailureStateEntity", b =>
                {
                    b.HasOne("Needly.Domain.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Needly.Infrastructure.GitHub.GitHubPullRequestStateEntity", b =>
                {
                    b.HasOne("Needly.Domain.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Needly.Infrastructure.GitHub.GitHubResponseStateEntity", b =>
                {
                    b.HasOne("Needly.Domain.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Needly.Infrastructure.GitHub.GitHubReviewRequestStateEntity", b =>
                {
                    b.HasOne("Needly.Domain.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Needly.Infrastructure.GitHub.GitHubReviewerFeedbackStateEntity", b =>
                {
                    b.HasOne("Needly.Domain.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
